#!/usr/bin/env python3
"""Generate Neovim colorschemes matching this rice's polybar/rofi/kitty/
VS Code themes.

Reuses generate-vscode-themes.py's own THEMES list, parse_theme_colors()
and resolve()/ROLE_CHAINS (loaded by file path, same convention as
generate-gtk-themes.py - a hyphenated filename can't be `import`ed
directly) rather than a second, separately-maintained copy of the same
per-theme color-resolution logic.

Writes each theme as a plain, dependency-free Neovim colorscheme file at
~/.config/nvim/colors/rice-<name>.lua (Neovim's own `colors/` runtimepath
convention - no plugin manager or `require()` wiring needed, `:colorscheme
rice-<name>` just finds it). polybar-theme.sh copies the picked one over
colors/current.lua and pushes `:colorscheme current` into every already-
open nvim instance via its RPC socket (see NVIM_CURRENT/serverstart there
and in lua/config/autocmds.lua) - the same "generate all themes up front,
activate by copy" split this rice already uses for kitty/starship/dunst/
rofi, not a new pattern.

Only the 28 base themes are covered, not their -square counterparts -
square-vs-rounded is a polybar-bar/rofi-window corner-radius concept with
no Neovim equivalent, so a theme and its square twin would produce
byte-identical colorscheme output (matching generate-vscode-themes.py's
and generate-gtk-themes.py's own existing base-only scope).

Usage:
    python3 generate-nvim-themes.py

Then either run polybar-theme.sh <name> (applies it as part of the normal
desktop theme switch) or, inside Neovim, ':colorscheme rice-<name>'
directly. Re-run any time after editing a polybar theme's [colors] block
to regenerate (idempotent - always overwrites its own output files).
"""
import importlib.util
import os

_here = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location(
    "generate_vscode_themes", os.path.join(_here, "generate-vscode-themes.py")
)
_vscode_gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_vscode_gen)

THEMES = _vscode_gen.THEMES
LIGHT_THEMES = _vscode_gen.LIGHT_THEMES
POLYBAR_THEMES_DIR = _vscode_gen.POLYBAR_THEMES_DIR
parse_theme_colors = _vscode_gen.parse_theme_colors
resolve = _vscode_gen.resolve

NVIM_CONFIG_DIR = os.path.expanduser("~/.config/nvim")
NVIM_COLORS_DIR = os.path.join(NVIM_CONFIG_DIR, "colors")
NVIM_PLUGINS_DIR = os.path.join(NVIM_CONFIG_DIR, "lua", "plugins")
NVIM_AUTOCMDS_PATH = os.path.join(NVIM_CONFIG_DIR, "lua", "config", "autocmds.lua")
NVIM_NORDIC_PLUGIN = os.path.join(NVIM_PLUGINS_DIR, "nordic.lua")
NVIM_RICE_PLUGIN = os.path.join(NVIM_PLUGINS_DIR, "rice-theme.lua")

# Marker substring used to detect an already-patched autocmds.lua (idempotent
# re-runs must not append a second copy).
AUTOCMD_MARKER = "/tmp/nvim-mgns-"

RICE_THEME_PLUGIN = """-- Colorscheme is generated by generate-nvim-themes.py (repo root, from
-- this rice's own polybar theme [colors] blocks) and switched live by
-- polybar-theme.sh, which copies the picked colors/rice-<name>.lua over
-- colors/current.lua. No plugin needed for "current" itself - it's a
-- plain Neovim colorscheme file, found on runtimepath like any other -
-- this just tells LazyVim to load it at startup instead of its own
-- default (tokyonight).
return {
  { "LazyVim/LazyVim", opts = { colorscheme = "current" } },
}
"""

AUTOCMD_SNIPPET = """
-- Own RPC server per instance, named like kitty's listen_on sockets
-- (/tmp/kitty-mgns-<PID>, see kitty.conf), so polybar-theme.sh can push a
-- live `:colorscheme current` into every already-open Neovim window on a
-- desktop theme switch - Neovim has no gsettings-style "theme changed"
-- signal an already-running instance reacts to on its own, unlike kitty's
-- `kitty @` or GTK's live re-theming, so this is the same explicit "loop
-- over sockets" mechanism as kitty's, not a copy-paste - Neovim needs it,
-- GTK doesn't. This file only loads on VeryLazy (see header above), by
-- which point an interactive session's UI is already attached, so the
-- nvim_list_uis() check below reliably tells apart a real terminal session
-- from a headless invocation (e.g. `nvim --headless +Lazy! sync` during
-- plugin install) - no interactive session to retint there, and starting a
-- server would just leak a socket no switch will ever reach.
if #vim.api.nvim_list_uis() > 0 then
  pcall(vim.fn.serverstart, "{marker}" .. vim.fn.getpid())
end
""".format(marker=AUTOCMD_MARKER)


def build_palette(c):
    base = c["base"]
    mantle = c["mantle"]
    surface0 = c.get("surface0", mantle)
    surface1 = c.get("surface1", surface0)
    text = c["text"]
    subtext = c["subtext"]
    return {
        "base": base,
        "mantle": mantle,
        "surface0": surface0,
        "surface1": surface1,
        "text": text,
        "subtext": subtext,
        "accent": resolve(c, "accent"),
        "red": resolve(c, "red"),
        "green": resolve(c, "green"),
        "yellow": resolve(c, "yellow"),
        "blue": resolve(c, "blue"),
        "cyan": resolve(c, "cyan"),
        "orange": resolve(c, "orange"),
        "pink": resolve(c, "pink"),
    }


# Ordered (group, opts) pairs, opts using palette role names resolved
# against the `p` table written into the Lua output (fg/bg/bold/italic/
# undercurl only - the small subset every group below actually needs).
# Covers core editor chrome + classic syntax groups + diagnostics/diff/
# gitsigns + the handful of LazyVim-default plugin groups (Telescope,
# neo-tree, WhichKey) most visibly on-screen, then links Neovim's
# built-in Treesitter @captures onto those same classic syntax groups -
# matching generate-vscode-themes.py's own scope (core editor + a
# reasonable, not exhaustive, token set), not a second design.
def build_groups(p):
    groups = [
        # --- editor chrome ---
        ("Normal", {"fg": p["text"], "bg": p["base"]}),
        ("NormalFloat", {"fg": p["text"], "bg": p["mantle"]}),
        ("FloatBorder", {"fg": p["surface1"], "bg": p["mantle"]}),
        ("Cursor", {"fg": p["base"], "bg": p["text"]}),
        ("CursorLine", {"bg": p["surface0"]}),
        ("CursorLineNr", {"fg": p["text"], "bold": True}),
        ("LineNr", {"fg": p["subtext"]}),
        ("SignColumn", {"fg": p["subtext"], "bg": p["base"]}),
        ("ColorColumn", {"bg": p["surface0"]}),
        ("VertSplit", {"fg": p["surface0"]}),
        ("WinSeparator", {"fg": p["surface0"]}),
        ("StatusLine", {"fg": p["text"], "bg": p["mantle"]}),
        ("StatusLineNC", {"fg": p["subtext"], "bg": p["mantle"]}),
        ("TabLine", {"fg": p["subtext"], "bg": p["mantle"]}),
        ("TabLineFill", {"bg": p["mantle"]}),
        ("TabLineSel", {"fg": p["base"], "bg": p["accent"]}),
        ("Pmenu", {"fg": p["text"], "bg": p["mantle"]}),
        ("PmenuSel", {"fg": p["base"], "bg": p["accent"]}),
        ("PmenuSbar", {"bg": p["surface0"]}),
        ("PmenuThumb", {"bg": p["surface1"]}),
        ("Visual", {"bg": p["surface1"]}),
        ("Search", {"fg": p["base"], "bg": p["yellow"]}),
        ("IncSearch", {"fg": p["base"], "bg": p["orange"]}),
        ("MatchParen", {"fg": p["accent"], "bold": True}),
        ("NonText", {"fg": p["surface1"]}),
        ("Whitespace", {"fg": p["surface1"]}),
        ("EndOfBuffer", {"fg": p["surface1"]}),
        ("Directory", {"fg": p["blue"]}),
        ("Title", {"fg": p["accent"], "bold": True}),
        ("ErrorMsg", {"fg": p["red"]}),
        ("WarningMsg", {"fg": p["yellow"]}),
        ("ModeMsg", {"fg": p["text"]}),
        ("MoreMsg", {"fg": p["green"]}),
        ("Question", {"fg": p["green"]}),
        # --- classic syntax groups ---
        ("Comment", {"fg": p["subtext"], "italic": True}),
        ("String", {"fg": p["green"]}),
        ("Number", {"fg": p["orange"]}),
        ("Boolean", {"fg": p["orange"]}),
        ("Constant", {"fg": p["orange"]}),
        ("Identifier", {"fg": p["text"]}),
        ("Function", {"fg": p["blue"]}),
        ("Statement", {"fg": p["accent"]}),
        ("Keyword", {"fg": p["accent"]}),
        ("Operator", {"fg": p["subtext"]}),
        ("Type", {"fg": p["yellow"]}),
        ("Structure", {"fg": p["yellow"]}),
        ("Special", {"fg": p["cyan"]}),
        ("Underlined", {"fg": p["blue"], "underline": True}),
        ("Todo", {"fg": p["base"], "bg": p["yellow"], "bold": True}),
        ("Error", {"fg": p["red"], "bold": True}),
        # --- diagnostics ---
        ("DiagnosticError", {"fg": p["red"]}),
        ("DiagnosticWarn", {"fg": p["yellow"]}),
        ("DiagnosticInfo", {"fg": p["blue"]}),
        ("DiagnosticHint", {"fg": p["cyan"]}),
        ("DiagnosticUnderlineError", {"undercurl": True, "sp": p["red"]}),
        ("DiagnosticUnderlineWarn", {"undercurl": True, "sp": p["yellow"]}),
        ("DiagnosticUnderlineInfo", {"undercurl": True, "sp": p["blue"]}),
        ("DiagnosticUnderlineHint", {"undercurl": True, "sp": p["cyan"]}),
        # --- diff / gitsigns ---
        ("DiffAdd", {"fg": p["green"], "bg": p["mantle"]}),
        ("DiffChange", {"fg": p["yellow"], "bg": p["mantle"]}),
        ("DiffDelete", {"fg": p["red"], "bg": p["mantle"]}),
        ("DiffText", {"fg": p["blue"], "bg": p["mantle"]}),
        ("GitSignsAdd", {"fg": p["green"]}),
        ("GitSignsChange", {"fg": p["yellow"]}),
        ("GitSignsDelete", {"fg": p["red"]}),
        # --- LazyVim-default plugin surfaces ---
        ("TelescopeNormal", {"fg": p["text"], "bg": p["mantle"]}),
        ("TelescopeBorder", {"fg": p["surface1"], "bg": p["mantle"]}),
        ("TelescopeSelection", {"bg": p["surface0"]}),
        ("TelescopePromptNormal", {"fg": p["text"], "bg": p["surface0"]}),
        ("NeoTreeNormal", {"fg": p["text"], "bg": p["mantle"]}),
        ("NeoTreeNormalNC", {"fg": p["text"], "bg": p["mantle"]}),
        ("NeoTreeDirectoryIcon", {"fg": p["blue"]}),
        ("NeoTreeDirectoryName", {"fg": p["blue"]}),
        ("NeoTreeRootName", {"fg": p["accent"], "bold": True}),
        ("WhichKeyFloat", {"bg": p["mantle"]}),
        ("WhichKey", {"fg": p["accent"]}),
    ]

    # Treesitter @captures link onto the classic groups above rather than
    # each getting its own color - one role resolution per rice theme,
    # not two, and every capture below already has an obvious classic
    # equivalent.
    links = {
        "@comment": "Comment",
        "@string": "String",
        "@number": "Number",
        "@boolean": "Boolean",
        "@constant": "Constant",
        "@constant.builtin": "Constant",
        "@keyword": "Keyword",
        "@keyword.function": "Keyword",
        "@keyword.return": "Keyword",
        "@keyword.operator": "Operator",
        "@conditional": "Keyword",
        "@repeat": "Keyword",
        "@function": "Function",
        "@function.call": "Function",
        "@function.builtin": "Function",
        "@method": "Function",
        "@method.call": "Function",
        "@type": "Type",
        "@type.builtin": "Type",
        "@variable": "Identifier",
        "@variable.parameter": "Identifier",
        "@variable.builtin": "Identifier",
        "@property": "Identifier",
        "@field": "Identifier",
        "@punctuation": "Operator",
        "@punctuation.bracket": "Operator",
        "@punctuation.delimiter": "Operator",
        "@operator": "Operator",
        "@tag": "Keyword",
        "@tag.attribute": "Type",
        "@tag.delimiter": "Operator",
    }

    return groups, links


def lua_bool(v):
    return "true" if v else "false"


def render_theme(name, c):
    p = build_palette(c)
    groups, links = build_groups(p)
    background = "light" if name in LIGHT_THEMES else "dark"

    lines = []
    lines.append(f"-- Rice theme \"{name}\" - generated by generate-nvim-themes.py from")
    lines.append(f"-- ~/.config/polybar/themes/{name}.ini's own [colors] block. Do not edit")
    lines.append("-- by hand - re-run the generator after changing that file instead.")
    lines.append('vim.cmd("hi clear")')
    lines.append('if vim.fn.exists("syntax_on") == 1 then')
    lines.append('  vim.cmd("syntax reset")')
    lines.append("end")
    lines.append(f'vim.o.background = "{background}"')
    lines.append(f'vim.g.colors_name = "rice-{name}"')
    lines.append("")
    lines.append("local hl = vim.api.nvim_set_hl")
    lines.append("")

    for group, opts in groups:
        parts = []
        for key in ("fg", "bg", "sp"):
            if key in opts:
                parts.append(f'{key} = "{opts[key]}"')
        for key in ("bold", "italic", "underline", "undercurl"):
            if opts.get(key):
                parts.append(f"{key} = {lua_bool(True)}")
        lines.append(f'hl(0, "{group}", {{ {", ".join(parts)} }})')

    lines.append("")
    for capture, target in links.items():
        lines.append(f'hl(0, "{capture}", {{ link = "{target}" }})')
    lines.append("")

    return "\n".join(lines)


# Wires an already-installed LazyVim config (e.g. from install_lazyvim in
# post-install-fedora.sh/post-install-opensuse.sh) into the rice system:
# drops the fixed Nordic default in favor of "current", and adds the
# RPC-server autocmd polybar-theme.sh's live-switch step depends on. A
# no-op (with an explanatory skip message, not a hard failure) if ~/.config/
# nvim doesn't exist - Neovim/LazyVim setup is a separate, independent,
# opt-in step this script doesn't own or require.
def wire_nvim_config():
    if not os.path.isdir(NVIM_CONFIG_DIR):
        print(f"skip Neovim wiring: {NVIM_CONFIG_DIR} not found (set up LazyVim first)")
        return

    os.makedirs(NVIM_PLUGINS_DIR, exist_ok=True)
    if os.path.isfile(NVIM_NORDIC_PLUGIN):
        os.remove(NVIM_NORDIC_PLUGIN)
        print(f"removed {NVIM_NORDIC_PLUGIN} (superseded by rice-theme.lua)")
    with open(NVIM_RICE_PLUGIN, "w", encoding="utf-8") as f:
        f.write(RICE_THEME_PLUGIN)
    print(f"wrote {NVIM_RICE_PLUGIN}")

    os.makedirs(os.path.dirname(NVIM_AUTOCMDS_PATH), exist_ok=True)
    existing = ""
    if os.path.isfile(NVIM_AUTOCMDS_PATH):
        with open(NVIM_AUTOCMDS_PATH, encoding="utf-8") as f:
            existing = f.read()
    if AUTOCMD_MARKER in existing:
        print(f"{NVIM_AUTOCMDS_PATH} already has the RPC-server autocmd, leaving it")
    else:
        with open(NVIM_AUTOCMDS_PATH, "a", encoding="utf-8") as f:
            f.write(AUTOCMD_SNIPPET)
        print(f"appended RPC-server autocmd to {NVIM_AUTOCMDS_PATH}")

    # Seed an initial current.lua only if one doesn't exist yet - never
    # stomp whatever theme the user (or a previous run) already picked.
    current_path = os.path.join(NVIM_COLORS_DIR, "current.lua")
    if not os.path.isfile(current_path):
        seed_path = os.path.join(NVIM_COLORS_DIR, "rice-catppuccin-mocha.lua")
        if os.path.isfile(seed_path):
            with open(seed_path, encoding="utf-8") as f:
                content = f.read()
            with open(current_path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"seeded {current_path} from rice-catppuccin-mocha.lua (run polybar-theme.sh <name> to switch)")


def main():
    os.makedirs(NVIM_COLORS_DIR, exist_ok=True)
    written = 0
    for name in THEMES:
        ini_path = os.path.join(POLYBAR_THEMES_DIR, f"{name}.ini")
        if not os.path.isfile(ini_path):
            print(f"skip {name}: {ini_path} not found")
            continue
        c = parse_theme_colors(ini_path)
        out_path = os.path.join(NVIM_COLORS_DIR, f"rice-{name}.lua")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(render_theme(name, c))
        written += 1
        print(f"wrote {out_path}")

    print(f"\n{written} colorschemes written to {NVIM_COLORS_DIR}")

    wire_nvim_config()

    print("\nRun polybar-theme.sh <name> to apply one, or ':colorscheme rice-<name>' inside Neovim.")


if __name__ == "__main__":
    main()
